In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [2]:
df_fig211=pd.read_csv("Copy of Appendix_2_Data_for_Figure_2.1-1.csv")
df_SDG_Global_countries_Index_2022=pd.read_csv("Data_SDG_Global_countries_Index_2022.csv")
df_SDG_Global_countries_specific_sdg_indicators=pd.read_csv("Data_SDG_Global_countries_specific_sdg_indicators.csv")
df_fig211.shape,df_SDG_Global_countries_Index_2022.shape,df_SDG_Global_countries_specific_sdg_indicators.shape

((147, 12), (193, 3), (193, 3))

In [13]:
df_fig211.head()

,RANK,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,1,Finland,7.821,7.886,7.756,2.518,1.892,1.258,0.775,0.736,0.109,0.534
1,2,Denmark,7.636,7.710,7.563,2.226,1.953,1.243,0.777,0.719,0.188,0.532
2,3,Iceland,7.557,7.651,7.464,2.320,1.936,1.320,0.803,0.718,0.270,0.191
3,4,Switzerland,7.512,7.586,7.437,2.153,2.026,1.226,0.822,0.677,0.147,0.461
4,5,Netherlands,7.415,7.471,7.359,2.137,1.945,1.206,0.787,0.651,0.271,0.419

In [4]:
df_SDG_Global_countries_Index_2022.head()

   Country  2022 SDG Index Score  2022 SDG Index Rank
0  Finland                  86.5                  1.0
1  Denmark                  85.6                  2.0
2   Sweden                  85.2                  3.0
3   Norway                  82.3                  4.0
4  Austria                  82.3                  5.0

In [6]:
df_happiness_sdg=df_fig211.merge(df_SDG_Global_countries_Index_2022)
df_happiness_sdg.shape

(111, 14)

In [12]:
df_happiness_sdg_sdg3=df_SDG_Global_countries_specific_sdg_indicators.merge(df_fig211).merge(df_SDG_Global_countries_Index_2022)
df_happiness_sdg_sdg3.shape

(111, 16)

In [3]:
df_SDG_Global_countries_specific_sdg_indicators.head()

    id      Country  sdg3_ncds
0  AFG  Afghanistan      35.27
1  ALB      Albania      11.40
2  DZA      Algeria      13.86
3  AND      Andorra        NaN
4  AGO       Angola      22.25

In [9]:
df_fig211[['Happiness score','Explained by: Healthy life expectancy','Explained by: Social support','Explained by: GDP per capita']].describe()

,Happiness score,Explained by: Healthy life expectancy,Explained by: Social support,Explained by: GDP per capita
count,146.000000,146.000000,146.000000,146.000000
mean,5.553575,0.586171,0.905863,1.410445
std,1.086843,0.176336,0.280122,0.421663
min,2.404000,0.000000,0.000000,0.000000
25%,4.888750,0.463250,0.732000,1.095500
50%,5.568500,0.621500,0.957500,1.445500
75%,6.305000,0.719750,1.114250,1.784750
max,7.821000,0.942000,1.320000,2.209000

In [10]:
df_fig211[['Happiness score','Explained by: Healthy life expectancy','Explained by: Social support','Explained by: GDP per capita']].corr()

,Happiness score,Explained by: Healthy life expectancy,Explained by: Social support,Explained by: GDP per capita
Happiness score,1.000000,0.740260,0.777889,0.763677
Explained by: Healthy life expectancy,0.740260,1.000000,0.666760,0.815386
Explained by: Social support,0.777889,0.666760,1.000000,0.722421
Explained by: GDP per capita,0.763677,0.815386,0.722421,1.000000

In [21]:
df_happiness_sdg_sdg3[['Happiness score','Explained by: Healthy life expectancy','Explained by: Social support','Explained by: GDP per capita','2022 SDG Index Score']].corr()

,Happiness score,Explained by: Healthy life expectancy,Explained by: Social support,Explained by: GDP per capita,2022 SDG Index Score
Happiness score,1.000000,0.757404,0.828222,0.820229,0.792632
Explained by: Healthy life expectancy,0.757404,1.000000,0.723927,0.864283,0.903477
Explained by: Social support,0.828222,0.723927,1.000000,0.792680,0.793085
Explained by: GDP per capita,0.820229,0.864283,0.792680,1.000000,0.868436
2022 SDG Index Score,0.792632,0.903477,0.793085,0.868436,1.000000

In [13]:
df_happiness_sdg_sdg3.head()

,id,Country,sdg3_ncds,RANK,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,2022 SDG Index Score,2022 SDG Index Rank
0,AFG,Afghanistan,35.27,146,2.404,2.469,2.339,1.263,0.758,0.000,0.289,0.000,0.089,0.005,52.5,147.0
1,ALB,Albania,11.40,90,5.199,5.321,5.076,1.718,1.439,0.646,0.719,0.511,0.138,0.028,71.6,61.0
2,DZA,Algeria,13.86,96,5.122,5.215,5.030,1.744,1.363,0.970,0.643,0.146,0.106,0.150,71.5,64.0
3,ARG,Argentina,15.72,57,5.967,6.090,5.844,1.891,1.592,1.102,0.662,0.555,0.081,0.085,72.8,54.0
4,ARM,Armenia,19.93,82,5.399,5.519,5.278,1.654,1.434,0.820,0.668,0.558,0.054,0.210,71.1,66.0

In [16]:
df_happiness_sdg_sdg3.sort_values('Explained by: Social support',ascending=False).head()

,id,Country,sdg3_ncds,RANK,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,2022 SDG Index Score,2022 SDG Index Rank
41,ISL,Iceland,8.65,3,7.557,7.651,7.464,2.320,1.936,1.320,0.803,0.718,0.270,0.191,78.9,22.0
31,FIN,Finland,9.60,1,7.821,7.886,7.756,2.518,1.892,1.258,0.775,0.736,0.109,0.534,86.5,1.0
89,SVN,Slovenia,11.45,22,6.630,6.718,6.542,1.885,1.810,1.249,0.769,0.685,0.118,0.115,80.0,15.0
25,DNK,Denmark,10.77,2,7.636,7.710,7.563,2.226,1.953,1.243,0.777,0.719,0.188,0.532,85.6,2.0
75,NOR,Norway,8.69,8,7.365,7.440,7.290,1.925,1.997,1.239,0.786,0.728,0.217,0.474,82.3,4.0

In [14]:
df_happiness_sdg_sdg3[['Happiness score','Explained by: Healthy life expectancy','Explained by: Social support','Explained by: GDP per capita','2022 SDG Index Score','sdg3_ncds']].corr()

,Happiness score,Explained by: Healthy life expectancy,Explained by: Social support,Explained by: GDP per capita,2022 SDG Index Score,sdg3_ncds
Happiness score,1.000000,0.757404,0.828222,0.820229,0.792632,-0.654468
Explained by: Healthy life expectancy,0.757404,1.000000,0.723927,0.864283,0.903477,-0.803024
Explained by: Social support,0.828222,0.723927,1.000000,0.792680,0.793085,-0.534824
Explained by: GDP per capita,0.820229,0.864283,0.792680,1.000000,0.868436,-0.673018
2022 SDG Index Score,0.792632,0.903477,0.793085,0.868436,1.000000,-0.652479
sdg3_ncds,-0.654468,-0.803024,-0.534824,-0.673018,-0.652479,1.000000